PISystem/Models/ErrorViewModel.cs
namespace PISystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PISystem/Models/Interface/IUserInformation.cs
using Microsoft.AspNetCore.Mvc;

namespace PISystem.Models.Interface
{
    public interface IUserInformation
    {
        UserInformationViewModel Model { get; set; }
        IActionResult Register();
        bool Login(string userName, string password);
    }
}

PISystem/Models/UserInformation.cs
using Microsoft.AspNetCore.Mvc;
using PISystem.Models.Interface;

namespace PISystem.Models
{
    public class UserInformation : IUserInformation
    {
        public UserInformationViewModel Model { get; set; }
        public readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserInformation(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            Model = new UserInformationViewModel();
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Register()
        {
            _context.UserInformations.Add(Model);
            _context.SaveChanges();
            return new OkResult();
        }





        public bool Login(string userName, string password)
        {
            var user = _context.UserInformations
                .FirstOrDefault(u => u.user_name == userName && u.password == password);

            if (user != null)
            {
                var userId = user.user_id;
                var user_Name = user.user_name;
                _httpContextAccessor.HttpContext.Session.SetString("UserId", userId.ToString());
                _httpContextAccessor.HttpContext.Session.SetString("UserName", user_Name.ToString());
                return true;
            }
            return false;
        }

    }

    public class UserInformationViewModel
    {
        public Guid user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public bool? is_active { get; set; }

    }
}

PISystem/Controllers/Bibhgiya_KarmachariController.cs
using Microsoft.AspNetCore.Mvc;

namespace PISystem.Controllers
{
    public class Bibhgiya_KarmachariController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PISystem/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace PISystem.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PISystem/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PISystem.Models;

namespace PISystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PISystem/Controllers/KarmachariBibaranController.cs
using Microsoft.AspNetCore.Mvc;

namespace PISystem.Controllers
{
    public class KarmachariBibaranController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

PISystem/Controllers/PratibedanController.cs
using Microsoft.AspNetCore.Mvc;

namespace PISystem.Controllers
{
    public class PratibedanController : Controller
    {

        
        public IActionResult Index()
        {
          return View();
        }

    }
}

PISystem/Controllers/UserInformationController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using PISystem.Models.Interface;

namespace PISystem.Controllers
{
    public class UserInformationController : Controller
    {
        private readonly IUserInformation _userInformation;

        public UserInformationController(IUserInformation userInformation)
        {
            _userInformation = userInformation;
        }



        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Indes()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(IFormCollection frm)
        {

            var userName = frm["user_name"].ToString();
            var password = frm["password"].ToString();
            var role = frm["role"].ToString();
            _userInformation.Model.user_name = userName;
            _userInformation.Model.password = password;
            _userInformation.Register();
            return View(frm);
        }

        [HttpPost]
        public IActionResult Login(IFormCollection frm)
        {
            var userName = frm["user_name"].ToString();
            var password = frm["password"].ToString();

            var isAuthenticated = _userInformation.Login(userName, password);
            if (isAuthenticated)
            {
                var claims = new[]
            {
                new Claim(ClaimTypes.Name, userName),
            };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                TempData["SuccessMessage"] = "Login successful.";
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                TempData["ErrorMessage"] = "Invalid UserName Or Password.";
                //ModelState.AddModelError("", "Invalid username or password.");
                return RedirectToAction("Index", "UserInformation");
            }
        }

    }
}

PISystem/Views/Bibhgiya_Karmachari/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PISystem/Views/Dashboard/Index.cshtml
<div class="text-center">
    DASHBOARD
</div>

PISystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
 

PISystem/Views/KarmachariBibaran/Index.cshtml
@page "/karmacharibibaran"
<p>Karmachari bibaran</p>

PISystem/Views/Pratibedan/Index.cshtml
pratibedan

PISystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - banking</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>



    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="plugins/summernote/summernote-bs4.min.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>


<body class="hold-transition sidebar-mini layout-fixed">



    @{

        string[] pathsToCheck = { "/Home","/Dashboard", "/KarmachariBibaran", "/Pratibedan" };
        if (pathsToCheck.Any(path => Context.Request.Path.Value.Contains(path)))
        {
            @Html.Partial("_Sidebar")
            @Html.Partial("_Messages")
        }
    }

    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-9">
            <main role="main">
                @RenderBody()

            </main>
        </div>
        <div class="col-md-1">
        </div>
    </div>



    <script>
        document.addEventListener('DOMContentLoaded', function () {
            setTimeout(function () {
                var successMessage = document.getElementById('success-message');
                var errorMessage = document.getElementById('error-message');

                if (successMessage) {
                    successMessage.style.transition = 'opacity 0.5s ease-out';
                    successMessage.style.opacity = 0;
                    setTimeout(function () {
                        successMessage.style.display = 'none';
                    }, 500);
                }

                if (errorMessage) {
                    errorMessage.style.transition = 'opacity 0.5s ease-out';
                    errorMessage.style.opacity = 0;
                    setTimeout(function () {
                        errorMessage.style.display = 'none';
                    }, 500);
                }
            }, 2000);
        });
    </script>




    <!-- jQuery -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="plugins/moment/moment.min.js"></script>
    <script src="plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="dist/js/pages/dashboard.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PISystem/Views/Shared/_Messages.cshtml
<style>
    .alert-dismissible {
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 1050; /* Ensure it is above other elements */
        width: 300px;
    }

    .alert .close {
        position: absolute;
        top: 0;
        right: 10px;
        padding: 0.75rem 1.25rem;
        color: inherit;
    }
</style>

@* Views/Shared/_Messages.cshtml *@
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" id="success-message" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" id="error-message" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

PISystem/Views/Shared/_Sidebar.cshtml
<!DOCTYPE html>
<html lang="en">

    <div class="wrapper">

        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
              <!-- <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
              </li> -->
            <li>
                <a class="nav-item d-none d-sm-inline-block" href="/dashboard">
                <img src="/images/nepgov.png" style="height: 40px; width: auto; margin-right: 10px;">
                सामाजिक विकास, कर्णाली प्रदेश, सुर्खेत ।
            </a>
            </li>
            </ul>
           
        </nav>
      
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
            <img src="/images/nepgov.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light"> कर्मचारी सूचना प्रणाली</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                         @{
                            var username = Context.Session.GetString("UserName");
                            if (!string.IsNullOrEmpty(username))
                            {
                                <span class="d-block" style="color:white">Welcome, @username |  <a class="nav-link" href="/UserInformation/Index">Logout</a></span>
                            }

                        } 
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">



                    <li class="nav-item">
                        
                            @Html.ActionLink("DashBoard", "Index", "Dashboard", null, new { @class = "nav-link" })
                          
                    </li>



                    <!-- Karmachari Bibaran -->
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-chart-pie"></i>
                            <p>
                                कर्मचारी बिबरण
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                          
                            <li class="nav-item">
                                @Html.ActionLink("karmachari Bibaran one", "Index", "KarmachariBibaran", null, new { @class = "nav-link" })
                            </li>
                        </ul>
                      
                    </li>

                    <!-- Bibhagiya Karbahi -->
                    <li class="nav-item">
                        <a href="/karmacharibibaran" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                          <p>
                             बिभागिय कारबाही
                           </p>

 
                        </a>
                    </li>



                    <!-- Pratibedan -->
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-chart-pie"></i>
                            <p>
                                Pratibedan
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                           
                            <li class="nav-item">
                                @Html.ActionLink("Pratibedan 1", "Index", "Pratibedan", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("karmachari Bibaran one", "Index", "KarmachariBibaran", null, new { @class = "nav-link" })
                            </li>

                        </ul>

                    </li>


                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
      
      
      

    
    </div>
   

</html>

PISystem/Views/UserInformation/Indes.cshtml
@{
    ViewData["Title"] = "User Information";
}

<section class="vh-100">
    <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                     class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                <form action="~/UserInformation/Register" method="post">
                    <!-- Email input -->
                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label" for="user_name">user name</label>
                        <input type="text" id="name" name="user_name" class="form-control form-control-lg" />
                    </div>

                    <!-- Password input -->
                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label" for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control form-control-lg" />
                    </div>


                    <div data-mdb-input-init class="form-outline mb-4">
                        <button type="submit" class="btn btn-primary btn-lg btn-block w-100">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

PISystem/Views/UserInformation/Index.cshtml
@{
    ViewData["Title"] = "User Information";
}

<section class="vh-100">
    <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                     class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                <form action="~/UserInformation/Login" method="post">
                    <!-- Email input -->
                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label" for="user_name">user name</label>
                        <input type="text" id="name" name="user_name" class="form-control form-control-lg" />
                    </div>

                    <!-- Password input -->
                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label" for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control form-control-lg" />
                    </div>


                    <div data-mdb-input-init class="form-outline mb-4">
                        <button type="submit" class="btn btn-primary btn-lg btn-block w-100">Login</button>
                    </div>
                </form>
               
            </div>
        </div>
    </div>
</section>